### ISSUE TITLE
Unable to connect to other pods

### ISSUE THREAD

**Issue by anmol26s** [aymhce/diaspora_ynh#3]
I am unable to connect to other pods. I can se my self on other pods but I can not see others on my pod.

**Comment by aymhce** [comment]
Normally, you can use "Search" field in top bar without issue for retrive users on others diaspora pods. Otherwise for your specific issue, I think you would be use a auto-signed certificate. In this case, others diaspora pods refuse to connect to your pod. So I think you have to get a valid certificate. For help, follow this link :  https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#Do_I_need_a_commercial_SSL_certificate.3F_.2F_Can_I_use_CAcert_certificates.3F
I'm sorry, is not easy to configure Diaspora pod.
